# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNFirebaseStarter' do
  # Pods for RNFirebaseStarter
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.3.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Database', '~> 6.3.0'
  pod 'Firebase/Functions', '~> 6.3.0'
  pod 'Firebase/DynamicLinks', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/RemoteConfig', '~> 6.3.0'
  pod 'Firebase/Storage', '~> 6.3.0'
  pod 'Firebase/Performance', '~> 6.3.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.2'

end

target 'RNFirebaseStarter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseStarter-tvOS

  target 'RNFirebaseStarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
